### ISSUE TITLE
Project Goals

### ISSUE THREAD

**Issue by abueide** [TokTok/toktok#10]
I'm just curious what goals this project has to differentiate itself from antox, and why its being written from scratch. (I haven't look at source code for either, just looking for an overhead view of the difference of goals between the projects)

**Comment by zetok** [comment]
Quotes from some time ago by the person who was maintaining Antox:

```
I'm going through the recommended code fixes
there are over 2000 of them
---
turn that smile upside down
then DROP TABLE FRIENDS;
because you're looking in antox database code
---
my brain just ;_;
---
I need to start a blog.
"Antox code gems"
---
you use the minimum of both
obviously
it's so clear
you don't even need docs
you should just know
```

That would be about Antox some time ago. I don't know whether that has changed, but at the time it did look like starting again clean would be of less effort than fixing things.

And so, TokTok client started as a GSoC project.

**Comment by abueide** [comment]
@zetok allright thanks
