### ISSUE TITLE
Run TokTok in Android Studio

### ISSUE THREAD

**Issue by vassad** [TokTok/toktok#6]
Hey!
I am trying to run TokTok on my Nexus 7, just upgraded to 23 API. I am using Android Studio 2.2.2.
And getting this error:

Error:Could not find jp.leafytree.gradle:gradle-android-scala-plugin:1.5-SNAPSHOT.

1) Tried to change it to the last one accessible from repos:
jp.leafytree.gradle:gradle-android-scala-plugin:1.4

now getting this error:
Error:(17, 0) Could not find matching constructor for: org.gradle.api.internal.tasks.DefaultScalaSourceSet(java.lang.String, org.gradle.api.internal.file.BaseDirFileResolver)

blames on this line in build.gradle:
apply plugin: 'jp.leafytree.android-scala'

Yet couldn't solve the issue.. perhaps the Android Studio version is incorrect? The Scala plugins I have reinstalled...

**Comment by iphydf** [comment]
Hi, thanks for your report. I need to add this to the documentation.

The reason for this is that the gradle-android-scala-plugin has not been released with the patches required to work with recent versions of the android gradle plugin. You will need to manually install it like so:

``` sh
$ git clone --depth=1 https://github.com/saturday06/gradle-android-scala-plugin
$ cd gradle-android-scala-plugin
$ ./gradlew install
```

After this, you should be able to load the project into Android Studio and use all the cool new features like instant code reloading.

**Comment by iphydf** [comment]
You're very welcome to contribute a documentation update, as well :).

**Comment by vassad** [comment]
@iphydf Thanks! Will try tomorrow and will contribute :)

**Comment by vassad** [comment]
Created a PR with documentation update. The @iphydf solution above works

> $ git clone --depth=1 https://github.com/saturday06/gradle-android-scala-plugin
> $ cd gradle-android-scala-plugin
> $ ./gradlew install

Can mark this issue as solved 👍
